import type { Metadata } from "next";
import "../styles/globals.scss";
import React from 'react';

export const metadata: Metadata = {
  title: "ZheXian",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh_cn">
      <body>
        {children}
      </body>
    </html>
  );
}
